// firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // 🔥 تم تفعيل الويندوز هنا
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4VH16eSATi2Bm4ZsAZ5zfb_tQ_eQIu8w',
    appId: '1:832689720513:web:9a56c2059dc107e74ad840',
    messagingSenderId: '832689720513',
    projectId: 'skincare-app-2a31f',
    authDomain: 'skincare-app-2a31f.firebaseapp.com',
    storageBucket: 'skincare-app-2a31f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALGef4_M_ZX_e52Zv1RbPcmW7yptpP4kY',
    appId: '1:832689720513:android:6cc1bab3dabeb3684ad840',
    messagingSenderId: '832689720513',
    projectId: 'skincare-app-2a31f',
    storageBucket: 'skincare-app-2a31f.firebasestorage.app',
  );
}
